In [1]:
import pandas as pd
import json

In [2]:
movies = pd.read_csv("movies.csv")
credits = pd.read_csv("credits.csv")

In [3]:
movies.shape , credits.shape

((4803, 20), (4803, 4))

In [4]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [5]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [6]:
movies["genres"][0] #it is in string

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [7]:
json.loads(movies["genres"][0])#now due to json it is converted in list of dictionaries from strings

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [8]:
json.loads(movies["genres"][0])[0]['name']

'Action'

### DATA MERGING

In [9]:
movie_credits = pd.merge(movies,credits, left_on="id", right_on="movie_id")
movie_credits.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movie_credits.shape

(4803, 24)

In [11]:
movie_credits.columns #title_x and title_y contains same data inside only column names are different 
# so we can use any column for cleaning

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')

### DATA CLEANING

In [12]:
movie_credits = movie_credits[["movie_id","title_x","overview","genres","keywords","cast","crew"]]
movie_credits.head()

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
movie_credits.dropna(inplace = True)

In [14]:
movie_credits.shape #only 3 rows was deleted

(4800, 7)

In [15]:
values = json.loads(movies["genres"][0])
values

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [16]:
values = json.loads(movies["genres"][0])  #to just fetch names
[value["name"] for value in values]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [17]:
def extract_values(str_lst):
    values = json.loads(str_lst)
    return [value["name"] for value in values]

In [18]:
extract_values(movies["genres"][0])

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [19]:
movie_credits["genres"] = movie_credits["genres"].apply(extract_values)

In [20]:
movie_credits["keywords"] = movie_credits["keywords"].apply(extract_values)

In [21]:
movie_credits

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [22]:
movie_credits["cast"].apply(extract_values)

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4798    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4799    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4800    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4801    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4802    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4800, dtype: object

In [23]:
movie_credits["cast"] = movie_credits["cast"].apply(extract_values).apply(lambda x:x[:3]) 
#lambda function is for temporary use
#(x:x[:3])->to fetch starting 3 values from every list

In [24]:
movie_credits["cast"]

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4798    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4799         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4800           [Eric Mabius, Kristin Booth, Crystal Lowe]
4801            [Daniel Henney, Eliza Coupe, Bill Paxton]
4802    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4800, dtype: object

In [25]:
json.loads(movie_credits["crew"][0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [26]:
def fetch_director(str_lst):
    values = json.loads(str_lst)
    return [value["name"] for value in values if value["job"] == "Director"]

In [27]:
movie_credits["crew"] = movie_credits["crew"].apply(fetch_director)

In [28]:
movie_credits

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns]
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [29]:
movie_credits["overview"] = movie_credits["overview"].str.split()

In [30]:
movie_credits.head()

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:
def collapse(lst):
    final_lst = []
    for i in lst:
        final_lst.append(i.replace(" ",""))
    return final_lst

In [32]:
movie_credits["cast"] = movie_credits["cast"].apply(collapse)
movie_credits["genres"] = movie_credits["genres"].apply(collapse)
movie_credits["crew"] = movie_credits["crew"].apply(collapse)
movie_credits["keywords"] = movie_credits["keywords"].apply(collapse)

In [33]:
movie_credits

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4799,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns]
4800,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4801,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4802,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]","[BrianHerzlinger, JonGunn, BrettWinn]"

In [34]:
movie_credits["tags"] = movie_credits["overview"] + movie_credits["genres"] + movie_credits["keywords"] + movie_credits["cast"] + movie_credits["crew"]

In [35]:
movie_credits.head()

,movie_id,title_x,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [36]:
final_df = movie_credits[["movie_id", "title_x", "tags"]]
final_df

,movie_id,title_x,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4798,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4799,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4800,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4801,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4802,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [37]:
final_df["tags"] = final_df["tags"].apply(lambda x: " ".join(x))

C:\Users\DELL\AppData\Local\Temp\ipykernel_7656\2382512077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["tags"] = final_df["tags"].apply(lambda x: " ".join(x))

In [38]:
final_df["tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [39]:
final_df.head()

,movie_id,title_x,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [40]:
final_df.columns

Index(['movie_id', 'title_x', 'tags'], dtype='object')

In [41]:
final_df.rename({"title_x" : "title"}, axis = 1, inplace = True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_7656\2984435692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.rename({"title_x" : "title"}, axis = 1, inplace = True)

In [42]:
final_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [43]:
final_df["tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [44]:
import nltk

In [45]:
from nltk.stem.porter import PorterStemmer

In [46]:
ps = PorterStemmer()

ps.stem("love")    #already defined by algorithm

'love'

In [47]:
def stem(txt):
    lst = []
    for i in txt.split():
        lst.append(ps.stem(i))
    return " ".join(lst)

In [48]:
final_df["tags"] = final_df["tags"].apply(lambda x: x.lower())

C:\Users\DELL\AppData\Local\Temp\ipykernel_7656\2425315478.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["tags"] = final_df["tags"].apply(lambda x: x.lower())

In [49]:
final_df["tags"] = final_df["tags"].apply(stem)

C:\Users\DELL\AppData\Local\Temp\ipykernel_7656\1628141165.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["tags"] = final_df["tags"].apply(stem)

In [50]:
print(final_df["tags"].iloc[0][:100])

in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom

In [51]:
final_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

In [53]:
cv = CountVectorizer(max_features=5000, stop_words="english")

In [54]:
vector = cv.fit_transform(final_df["tags"])

In [55]:
vector.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [56]:
list(cv.get_feature_names_out()) #these are 5000 unique words used in ovweview of every movie

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [57]:
final_df.shape

(4800, 3)

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
similarity = cosine_similarity(vector)

In [60]:
similarity.shape

(4800, 4800)

In [61]:
similarity

array([[1.        , 0.08585457, 0.08718573, ..., 0.04559608, 0.        ,
        0.        ],
       [0.08585457, 1.        , 0.06154575, ..., 0.02414023, 0.        ,
        0.02654659],
       [0.08718573, 0.06154575, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04559608, 0.02414023, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02654659, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

### Recommendation

In [62]:
final_df.reset_index(drop=True, inplace=True)

In [63]:
final_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4795,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4796,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4797,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4798,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4799,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [64]:
final_df[final_df["title"] == "Iron Man 2"]

    movie_id       title                                               tags
79     10138  Iron Man 2  with the world now awar of hi dual life as the...

In [65]:
vector = vector.toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [66]:
vector[79]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [67]:
movie_index = final_df[final_df["title"] == "Iron Man 2"].index[0]
movie_index

79

In [68]:
distances = similarity[movie_index]  #cosine similarity of "Iron Man 2" movie with other movies
distances

array([0.0631474 , 0.1114418 , 0.04526787, ..., 0.01775552, 0.16461885,
       0.09762721])

In [69]:
similar_movie = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])
similar_movie
#when a movie is compared to itself cosine similarity is 1

[(79, 1.0000000000000002),
 (3088, 0.4448508420389507),
 (182, 0.44353276257274377),
 (2023, 0.42878755134289176),
 (31, 0.4268716668090516),
 (2427, 0.4225001481984199),
 (3660, 0.41618316990641147),
 (3223, 0.40974071673083606),
 (697, 0.4085523860668957),
 (68, 0.4041894792106529),
 (4442, 0.3990621323554688),
 (2955, 0.3981852643823298),
 (2699, 0.3913918929198094),
 (4507, 0.3913918929198094),
 (3668, 0.39050882279227994),
 (20, 0.38936686733343034),
 (1140, 0.38545134418843735),
 (4302, 0.3821657633028298),
 (1813, 0.38147067284666075),
 (4245, 0.37929272024843746),
 (4015, 0.3754126674844049),
 (3606, 0.3735219680565763),
 (232, 0.37328844382740006),
 (4377, 0.37277743955795584),
 (3192, 0.3696106354772864),
 (2653, 0.36791710704733427),
 (3808, 0.36781658782309656),
 (4141, 0.3667434323290369),
 (3289, 0.36400491409951086),
 (2246, 0.3627711598098719),
 (60, 0.3624330466788679),
 (1199, 0.3606557377049181),
 (4447, 0.3606557377049181),
 (193, 0.36064519288355334),
 (610, 0.3578855969344618),
 (2977, 0.3578352677779973),
 (3619, 0.3578352677779973),
 (583, 0.3572156391438014),
 (4523, 0.35668048432773136),
 (1008, 0.35613687977442265),
 (857, 0.3548682087811991),
 (3334, 0.3530533855480204),
 (1248, 0.35154137266627783),
 (3481, 0.3510047385959568),
 (197, 0.35018775948591063),
 (3672, 0.34938244924235623),
 (1117, 0.3492961981392408),
 (7, 0.3474411464169823),
 (339, 0.3474411464169823),
 (2043, 0.3473107010786444),
 (313, 0.346274924279844),
 (4659, 0.346274924279844),
 (115, 0.34528978736392446),
 (482, 0.3452897873639244),
 (3069, 0.3452897873639244),
 (1566, 0.3451969550494724),
 (4788, 0.3449699264454673),
 (10, 0.34415494032603927),
 (4339, 0.3441282785273711),
 (1450, 0.3414316798210559),
 (4096, 0.34004178463910356),
 (3940, 0.3393433930764383),
 (1262, 0.3391779807375454),
 (1986, 0.3380045630924029),
 (1085, 0.33735489150850667),
 (4774, 0.3372929610533558),
 (2875, 0.33457295580894597),
 (2490, 0.33432539901899483),
 (4472, 0.33286192405583187),
 (409, 0.33264957192955785),
 (788, 0.33264957192955785),
 (530, 0.32937215631829414),
 (3796, 0.3293721563182941),
 (129, 0.32923769125601826),
 (813, 0.32923769125601826),
 (3632, 0.32813886050492774),
 (174, 0.3280369472418919),
 (3086, 0.32803694724189186),
 (2861, 0.3278688524590165),
 (3980, 0.3272672075485291),
 (1442, 0.32726720754852906),
 (3869, 0.32508330764384863),
 (2301, 0.3233419501518519),
 (3305, 0.32271748738401557),
 (4210, 0.32271748738401557),
 (1409, 0.3219454348727918),
 (3389, 0.3219454348727918),
 (4650, 0.32137001808599086),
 (942, 0.32092613663368996),
 (4458, 0.32092613663368996),
 (3297, 0.32065506721576614),
 (1937, 0.3203292174136482),
 (1641, 0.3200921998322399),
 (1616, 0.3195993709027958),
 (4668, 0.3195993709027958),
 (450, 0.3194292535910661),
 (1727, 0.3194292535910661),
 (2485, 0.3194292535910661),
 (3572, 0.3190988234211321),
 (4021, 0.3183930844410176),
 (2456, 0.31762040840214206),
 (2746, 0.31762040840214206),
 (1807, 0.3168751111488149),
 (282, 0.3165699246086372),
 (264, 0.31520500902563947),
 (493, 0.3145570470222877),
 (2945, 0.3145570470222877),
 (3539, 0.3141690401556935),
 (591, 0.31406031233096104),
 (3852, 0.314060312330961),
 (2995, 0.3139218769987531),
 (274, 0.3137883279443299),
 (2414, 0.31362502409359005),
 (2769, 0.31362502409359005),
 (2651, 0.31362502409359),
 (1999, 0.31256368425082626),
 (3165, 0.3120370390843952),
 (4512, 0.3117068102332409),
 (711, 0.311554869297948),
 (3387, 0.31094670840846167),
 (4407, 0.31094670840846167),
 (2506, 0.30918521429890955),
 (939, 0.30918521429890944),
 (2177, 0.30883657459287317),
 (2028, 0.30797365987311975),
 (196, 0.30753463803927367),
 (203, 0.3074140125637411),
 (2767, 0.3074140125637411),
 (3377, 0.3073393159249119),
 (3725, 0.3073393159249119),
 (4098, 0.30649148171402396),
 (3372, 0.30645550473491),
 (206, 0.3064142895501718),
 (2285, 0.30606668389141994),
 (2593, 0.3053857783007297),
 (1116, 0.30536653715914863),
 (171, 0.3047887380849036),
 (1230, 0.3047887380849036),
 (1536, 0.3047887380849036),
 (1319, 0.30390364135345915),
 (4145, 0.30389097843791985),
 (1135, 0.3029905587448635),
 (2655, 0.3029905587448635),
 (471, 0.30261718761258893),
 (4181, 0.3018438502970849),
 (1203, 0.30178582014172844),
 (2268, 0.30178582014172844),
 (1259, 0.3013211765710953),
 (2589, 0.30132117657109525),
 (2189, 0.30061412551478084),
 (4737, 0.3001621135579357),
 (640, 0.29944475857435754),
 (2937, 0.298982706574824),
 (954, 0.2989493323818781),
 (3292, 0.2989493323818781),
 (790, 0.29875271984342394),
 (1852, 0.2976796992865011),
 (3690, 0.2975308222082788),
 (3308, 0.29691798773226924),
 (4624, 0.29691798773226924),
 (1091, 0.29634779238509984),
 (3429, 0.29634779238509984),
 (4137, 0.29620141164394614),
 (1626, 0.2956885083818292),
 (1280, 0.29568850838182914),
 (1715, 0.29568850838182914),
 (2064, 0.2952820635046474),
 (868, 0.2950819672131148),
 (4779, 0.2950082946711551),
 (3084, 0.29424117463818517),
 (1037, 0.29373674772302333),
 (44, 0.29367288496594224),
 (518, 0.29349631925933584),
 (3101, 0.2930984861480607),
 (4638, 0.29288161709420996),
 (2219, 0.2918231329049255),
 (727, 0.29166534801482613),
 (706, 0.2908640121023909),
 (3841, 0.2908640121023909),
 (4149, 0.2907845446780848),
 (4482, 0.2903603510974963),
 (2499, 0.28993800854507673),
 (3954, 0.28993800854507673),
 (2565, 0.2897486791497955),
 (2903, 0.2897143873360593),
 (3163, 0.2897143873360593),
 (2346, 0.2895342886808186),
 (2355, 0.288082979849016),
 (3596, 0.28703232883665536),
 (2010, 0.2868599887857916),
 (4116, 0.2868599887857916),
 (1020, 0.2862991671569341),
 (1433, 0.28585836756192784),
 (443, 0.28580512163411176),
 (1017, 0.28580512163411176),
 (3256, 0.2854558688091882),
 (970, 0.28531022061928446),
 (2869, 0.28408832969137404),
 (3054, 0.2834217155626206),
 (3855, 0.2827957143221761),
 (1635, 0.2827861608970319),
 (69, 0.28226252168423105),
 (496, 0.2818601515271634),
 (1947, 0.2818254674500584),
 (30, 0.2813954885410108),
 (2021, 0.2813954885410108),
 (3635, 0.2813954885410108),
 (1365, 0.28090408296273767),
 (64, 0.28051474932731063),
 (1044, 0.28051474932731063),
 (1131, 0.28051474932731063),
 (3697, 0.2801414760424323),
 (2508, 0.27994401679440195),
 (1881, 0.27948154232004163),
 (2356, 0.2794815423200416),
 (1218, 0.2793993781135563),
 (2757, 0.2793993781135563),
 (3216, 0.2793993781135563),
 (3415, 0.2793993781135563),
 (2117, 0.27877779919430223),
 (2334, 0.27877779919430223),
 (3897, 0.27877779919430223),
 (4375, 0.27877779919430223),
 (423, 0.27868852459016397),
 (4269, 0.27868852459016397),
 (1774, 0.27775098981515434),
 (716, 0.277413239854608),
 (4633, 0.27723197625967927),
 (2230, 0.2772079766079648),
 (1179, 0.27659127289275987),
 (1882, 0.27659127289275987),
 (1897, 0.27659127289275987),
 (1907, 0.27659127289275987),
 (1982, 0.27659127289275987),
 (2381, 0.27659127289275987),
 (3375, 0.27623182989113954),
 (495, 0.276211078523504),
 (3360, 0.2759532298909644),
 (122, 0.2759532298909643),
 (1918, 0.27546001550227794),
 (3956, 0.27546001550227794),
 (1481, 0.2754491154759396),
 (4664, 0.27544911547593953),
 (1845, 0.27442189608189127),
 (1792, 0.27422922048096876),
 (2918, 0.273754364331662),
 (126, 0.2736387341831744),
 (1741, 0.27363873418317436),
 (4721, 0.27363873418317436),
 (710, 0.27351327721811325),
 (2251, 0.272975545216307),
 (3303, 0.272975545216307),
 (3803, 0.2726744612490832),
 (3802, 0.2719842087990874),
 (1217, 0.2716072381275556),
 (1416, 0.2716072381275556),
 (2105, 0.27134238459003635),
 (2148, 0.27134238459003635),
 (4726, 0.27134238459003635),
 (599, 0.2705272845936282),
 (560, 0.27030007985833593),
 (3467, 0.270232002768764),
 (304, 0.27001422005822157),
 (3649, 0.27001422005822157),
 (4127, 0.27001422005822157),
 (2344, 0.26997734714182076),
 (1811, 0.2689930556556346),
 (575, 0.26893123948667963),
 (1253, 0.2684792193590243),
 (682, 0.26792425767179356),
 (1687, 0.26792425767179356),
 (2912, 0.26792425767179356),
 (551, 0.267911729357851),
 (3614, 0.26746031921519586),
 (4598, 0.2669753499690384),
 (4597, 0.2667037114215397),
 (2933, 0.2665300196340371),
 (140, 0.26633280908566315),
 (1597, 0.26591730613478676),
 (4742, 0.26591730613478676),
 (277, 0.2654294092078785),
 (2980, 0.2644718419629145),
 (3505, 0.264363072950721),
 (3418, 0.26429211252186224),
 (893, 0.2641199165349501),
 (1247, 0.2638082705071977),
 (152, 0.2634977250546353),
 (26, 0.2631773073081477),
 (2152, 0.2631773073081477),
 (3440, 0.2631773073081477),
 (1855, 0.2623248648741171),
 (2207, 0.26229508196721313),
 (921, 0.26203509329175206),
 (664, 0.2615343689010107),
 (387, 0.2614653776396035),
 (1530, 0.26015668130770697),
 (3688, 0.26015668130770697),
 (1257, 0.25994801559480185),
 (851, 0.2599480155948018),
 (867, 0.2599480155948018),
 (3178, 0.2599480155948018),
 (4240, 0.2583180951504403),
 (4795, 0.2583180951504403),
 (2603, 0.25809808986444116),
 (3386, 0.25766925044124067),
 (3764, 0.25766925044124067),
 (3915, 0.25766925044124067),
 (4448, 0.25766925044124067),
 (4541, 0.25766925044124067),
 (4556, 0.25766925044124067),
 (4675, 0.25766925044124067),
 (869, 0.2568347534004199),
 (2797, 0.2568347534004199),
 (3895, 0.2568347534004199),
 (119, 0.25664471656093313),
 (3755, 0.25664471656093313),
 (335, 0.25607375986579195),
 (1095, 0.25607375986579195),
 (1953, 0.25607375986579195),
 (2362, 0.25607375986579195),
 (2373, 0.25607375986579195),
 (3512, 0.25607375986579195),
 (3568, 0.25607375986579195),
 (3684, 0.25607375986579195),
 (3919, 0.25607375986579195),
 (4233, 0.25607375986579195),
 (4277, 0.25607375986579195),
 (4397, 0.25607375986579195),
 (4794, 0.2548029145033651),
 (1535, 0.25450754480732873),
 (1112, 0.2543834855531591),
 (1067, 0.253830734814982),
 (545, 0.2538307348149819),
 (3510, 0.25295712740005066),
 (4572, 0.25295712740005066),
 (2463, 0.2525896007844686),
 (4305, 0.2525896007844686),
 (217, 0.2521809896771574),
 (673, 0.2521640072205116),
 (4376, 0.2521640072205116),
 (3549, 0.2511009804759127),
 (1148, 0.25100249018756765),
 (2086, 0.25100249018756765),
 (557, 0.25092971685670945),
 (3376, 0.25027511165626987),
 (592, 0.25003472945769345),
 (1090, 0.25003472945769345),
 (1241, 0.25003472945769345),
 (1705, 0.2499758908336389),
 (1411, 0.24967623556456983),
 (1425, 0.248973301616926),
 (4445, 0.24857728847995225),
 (1771, 0.24842803761781473),
 (3825, 0.24842803761781473),
 (1557, 0.2481259448693429),
 (3060, 0.2481259448693429),
 (2958, 0.24794235184023233),
 (2539, 0.24708589901564307),
 (4722, 0.24662126427459016),
 (903, 0.24640709031819094),
 (3837, 0.24622105247338447),
 (4329, 0.24622105247338447),
 (1192, 0.2460277104314189),
 (1454, 0.24602771043141888),
 (4453, 0.24602771043141888),
 (1476, 0.24567799069467633),
 (2113, 0.24567799069467633),
 (4297, 0.24567799069467633),
 (4750, 0.24567799069467633),
 (823, 0.2454141044845864),
 (1782, 0.2454141044845864),
 (1583, 0.24517195928059624),
 (3646, 0.24488966562419281),
 (4753, 0.24485334711313597),
 (2296, 0.24393057429501447),
 (3986, 0.24335429208339399),
 (4085, 0.24335429208339399),
 (2511, 0.24312291308276732),
 (4586, 0.24312291308276732),
 (96, 0.24293289905367482),
 (3857, 0.24293289905367482),
 (4062, 0.2429328990536748),
 (2686, 0.24278927923677465),
 (562, 0.24196695924791364),
 (4314, 0.24196695924791362),
 (4318, 0.24196695924791362),
 (21, 0.24153958130008232),
 (4516, 0.2406564354498285),
 (1342, 0.24027781497213457),
 (3975, 0.24027781497213455),
 (364, 0.24024691306023618),
 (185, 0.23995201439520175),
 (835, 0.23995201439520175),
 (246, 0.23976933297214997),
 (919, 0.23953506879020423),
 (2109, 0.23891584741279373),
 (139, 0.23821530630160656),
 (2778, 0.23821530630160656),
 (824, 0.2381437594292009),
 (1193, 0.23806401044239275),
 (4169, 0.23778277701823536),
 (1814, 0.23742458651628182),
 (4313, 0.23740728088656998),
 (1589, 0.23707823390807992),
 (2887, 0.2370782339080799),
 (103, 0.2364037567692296),
 (4352, 0.2364037567692296),
 (3662, 0.23577655583010979),
 (3102, 0.23539293971054817),
 (3108, 0.23539293971054817),
 (715, 0.23521876807019254),
 (2047, 0.23521876807019254),
 (2244, 0.23521876807019254),
 (2801, 0.23521876807019254),
 (2986, 0.23498939817841866),
 (205, 0.23498939817841863),
 (306, 0.23473427987697595),
 (1359, 0.23473427987697595),
 (4104, 0.2347117212031574),
 (469, 0.23463291717775303),
 (4161, 0.23430529367536795),
 (3092, 0.2340277793132964),
 (2682, 0.23392345092606678),
 (292, 0.2337622911060922),
 (1229, 0.2337622911060922),
 (1580, 0.2337622911060922),
 (4573, 0.2337622911060922),
 (2963, 0.23336574749384725),
 (1278, 0.2333657474938472),
 (1360, 0.2333657474938472),
 (1078, 0.2330737408884557),
 (4077, 0.2330737408884557),
 (3582, 0.23202921343386096),
 (71, 0.23162743094465488),
 (729, 0.23162743094465488),
 (1296, 0.23162743094465488),
 (1657, 0.23162743094465488),
 (3642, 0.23162743094465488),
 (3838, 0.23162743094465488),
 (4615, 0.23162743094465488),
 (3809, 0.23154046738576298),
 (164, 0.23154046738576295),
 (62, 0.2314128617175502),
 (1555, 0.23082176787424138),
 (2233, 0.23082176787424138),
 (1830, 0.23072199619554765),
 (4760, 0.23072199619554765),
 (3331, 0.23046638387921276),
 (1123, 0.22996102490913695),
 (1421, 0.22996102490913695),
 (3859, 0.22996102490913695),
 (809, 0.22955001291856497),
 (1188, 0.22950819672131145),
 (1307, 0.22903933372554727),
 (1346, 0.22903933372554727),
 (3027, 0.22903933372554727),
 (3633, 0.22903933372554727),
 (3989, 0.22903933372554727),
 (2074, 0.2286338344395713),
 (2345, 0.2286338344395713),
 (3099, 0.2286338344395713),
 (3355, 0.2286338344395713),
 (16, 0.22847357081849518),
 (576, 0.22847357081849518),
 (1614, 0.22847357081849518),
 (2788, 0.22847357081849518),
 (2852, 0.22847357081849518),
 (4218, 0.22805887471467656),
 (1312, 0.22764980017060304),
 (3153, 0.22764980017060304),
 (3156, 0.22764980017060304),
 (784, 0.22653609644731054),
 (900, 0.22653609644731054),
 (1825, 0.22653609644731054),
 (4063, 0.22653609644731051),
 (169, 0.2265069618453705),
 (1174, 0.22633936510629635),
 (2787, 0.22633936510629635),
 (4134, 0.22633936510629635),
 (3780, 0.22633936510629632),
 (1041, 0.22599088242832144),
 (3248, 0.22599088242832144),
 (3680, 0.22599088242832144),
 (3761, 0.22599088242832144),
 (3813, 0.22599088242832144),
 (3999, 0.22599088242832144),
 (137, 0.22587059132360013),
 (402, 0.22552540122880066),
 (922, 0.22552540122880066),
 (1380, 0.22552540122880066),
 (4672, 0.22491216083990842),
 (18, 0.22478374966139064),
 (1952, 0.22443836178655088),
 (3043, 0.22443836178655088),
 (4, 0.22411318083394582),
 (11, 0.22411318083394582),
 (543, 0.22411318083394582),
 (3937, 0.22411318083394582),
 (2668, 0.22406453988256797),
 (3266, 0.22406453988256794),
 (4164, 0.22351950249084504),
 (4777, 0.22351950249084504),
 (4128, 0.223519502490845),
 (2075, 0.22325977446487583),
 (4700, 0.22301880324035134),
 (4554, 0.22288359934599658),
 (40, 0.22268849079920192),
 (101, 0.22268849079920192),
 (112, 0.22268849079920192),
 (207, 0.22268849079920192),
 (5, 0.22242542101947538),
 (113, 0.22242542101947535),
 (1183, 0.22242542101947535),
 (1254, 0.22242542101947535),
 (1527, 0.22242542101947535),
 (4550, 0.22242542101947535),
 (1485, 0.22234616366476415),
 (4621, 0.22233428588149945),
 (636, 0.22176638128637186),
 (1155, 0.22176638128637183),
 (491, 0.22064350631794763),
 (27, 0.22046568747940454),
 (1304, 0.22046568747940454),
 (4006, 0.22046568747940454),
 (3793, 0.2198725261032593),
 (3233, 0.2195814375455294),
 (3795, 0.2195814375455294),
 (902, 0.2194917941706788),
 (1723, 0.2194917941706788),
 (3918, 0.2194917941706788),
 (3929, 0.2194917941706788),
 (4281, 0.2194917941706788),
 (1497, 0.21899072269923614),
 (4228, 0.2187592403366185),
 (750, 0.2185568577202031),
 (2258, 0.2185568577202031),
 (3103, 0.2185568577202031),
 (3050, 0.21838043617304562),
 (511, 0.21777026332312227),
 (1896, 0.21777026332312227),
 (2676, 0.21777026332312227),
 (3118, 0.21777026332312227),
 (3683, 0.21777026332312227),
 (230, 0.21745982800732075),
 (747, 0.2173745329155879),
 (2484, 0.21732171441573994),
 (388, 0.21728579050204447),
 (4060, 0.21728579050204447),
 (328, 0.2164218276749025),
 (512, 0.2164218276749025),
 (1836, 0.2164218276749025),
 (2161, 0.2164218276749025),
 (4661, 0.2164218276749025),
 (127, 0.21607911672722896),
 (1544, 0.21579360624026636),
 (3687, 0.21527424662749153),
 (1794, 0.21514499158934372),
 (2813, 0.21488337159486803),
 (3361, 0.21477985253575393),
 (1850, 0.21475059163974353),
 (486, 0.21446942702057076),
 (826, 0.21398266546446332),
 (1475, 0.21398266546446332),
 (4396, 0.21398266546446332),
 (4402, 0.21398266546446332),
 (796, 0.2135802799752307),
 (2708, 0.2135802799752307),
 (4529, 0.2135802799752307),
 (821, 0.21343583340452585),
 (130, 0.21339479988815996),
 (2433, 0.21311475409836064),
 (2319, 0.21306624726853052),
 (4311, 0.21306624726853052),
 (2790, 0.21306624726853046),
 (2850, 0.21306624726853046),
 (1884, 0.21273254894742138),
 (2966, 0.21273254894742138),
 (3820, 0.21242889541505994),
 (1780, 0.2123251450326003),
 (2623, 0.2113891001584171),
 (2673, 0.21104661640575811),
 (3810, 0.21104661640575811),
 (3923, 0.21104661640575811),
 (2054, 0.210386061995483),
 (4322, 0.210386061995483),
 (2380, 0.21018090732748373),
 (3641, 0.2099527225817517),
 (1170, 0.20979816635063125),
 (2080, 0.20979816635063125),
 (35, 0.2090833493957267),
 (771, 0.2090833493957267),
 (2186, 0.2090833493957267),
 (3222, 0.2090833493957267),
 (3772, 0.2090833493957267),
 (4199, 0.2090833493957267),
 (4459, 0.2090833493957267),
 (241, 0.20770324619863198),
 (2853, 0.20770324619863198),
 (1868, 0.20717387241835464),
 (1051, 0.20696492241822326),
 (1509, 0.20696492241822326),
 (2310, 0.20696492241822326),
 (3758, 0.20696492241822326),
 (4114, 0.20696492241822326),
 (4439, 0.20696492241822326),
 (4446, 0.20696492241822326),
 (4579, 0.20696492241822326),
 (1022, 0.2056157234061163),
 (1910, 0.205437082431117),
 (2874, 0.2053157732487465),
 (3270, 0.2053157732487465),
 (1176, 0.20531577324874647),
 (2102, 0.20502309202618244),
 (3181, 0.20502309202618244),
 (280, 0.2050230920261824),
 (1851, 0.20488325586666564),
 (1721, 0.20485900789263356),
 (4151, 0.20485900789263356),
 (1923, 0.2037054285956667),
 (2394, 0.2037054285956667),
 (3009, 0.2037054285956667),
 (3977, 0.2037054285956667),
 (4032, 0.2037054285956667),
 (1328, 0.20350678844252726),
 (316, 0.20334852822071928),
 (1908, 0.20334852822071928),
 (444, 0.20328584951250758),
 (4553, 0.20296250614016603),
 (649, 0.202444082544729),
 (1647, 0.202444082544729),
 (1945, 0.202444082544729),
 (2295, 0.2018535783723019),
 (1565, 0.20184778056447447),
 (3484, 0.20184778056447447),
 (448, 0.20174479174172594),
 (2082, 0.20174479174172594),
 (2099, 0.20174479174172594),
 (3724, 0.20174479174172594),
 (1143, 0.20120081132312223),
 (1451, 0.20120081132312223),
 (2467, 0.20120081132312223),
 (2605, 0.20120081132312223),
 (2765, 0.20120081132312223),
 (1397, 0.20088078438073018),
 (3598, 0.20088078438073018),
 (3972, 0.20088078438073018),
 (4221, 0.20088078438073018),
 (133, 0.20059523941139693),
 (2051, 0.20059523941139693),
 (2932, 0.20059523941139693),
 (2388, 0.20040941700985385),
 (1756, 0.2003797772231045),
 (3733, 0.20002778356615475),
 (4122, 0.1995310661777344),
 (114, 0.19917864129354076),
 (225, 0.19917864129354076),
 (1166, 0.19917864129354076),
 (3367, 0.19916847989561598),
 (1103, 0.19916847989561595),
 (2359, 0.19835388147218588),
 (4732, 0.19835388147218588),
 (2079, 0.19835388147218586),
 (1694, 0.19762329379097646),
 (2353, 0.19762329379097646),
 (567, 0.19756519492339994),
 (644, 0.1975651949233999),
 (1290, 0.1975651949233999),
 (2724, 0.1975651949233999),
 (4117, 0.1975651949233999),
 (607, 0.19753736687974843),
 (969, 0.19753736687974843),
 (2895, 0.19753736687974843),
 (3578, 0.19753736687974843),
 (3673, 0.19753736687974843),
 (3366, 0.19721624229023174),
 (359, 0.19712567225455277),
 (3701, 0.19712567225455277),
 (4653, 0.19712567225455277),
 (1329, 0.19672131147540983),
 (2723, 0.1961607830921235),
 (4781, 0.1961607830921235),
 (2802, 0.1955795646794894),

In [70]:
for index, score in similar_movie[:10]:
    print(final_df.iloc[index, 1])

Iron Man 2
Krrish
Ant-Man
The Animal
Iron Man 3
The Adventures of Elmo in Grouchland
Flying By
All Is Lost
The Truman Show
Iron Man

In [71]:
def recommender(movie_name):
    movie_index = final_df[final_df["title"] == movie_name].index[0]
    distances = similarity[movie_index]
    similar_movie = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])
    
    for index, score in similar_movie[:10]:
        print(final_df.iloc[index, 1])

In [72]:
recommender("Avatar")

Avatar
Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.
Battle: Los Angeles
Predators
Small Soldiers
Meet Dave